name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install linker
      run: sudo apt-get install lld
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-02-23
        target: x86_64-unknown-linux-gnu
        override: true
        components: rust-src
    - name: Build
      run: make


