name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install linker
      run: sudo apt-get install lld
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2022-02-23
        target: x86_64-unknown-linux-gnu
        components: rust-src
    - name: Create pseudo .env
      run: touch .env
    - name: Build
      run: make
